import { apiClient } from './apiClient';

// Mock data for development
const MOCK_MEMBERS = [
    { id: 1, name: 'Alex Johnson', email: 'alex@example.com', role: 'Administrator', status: 'Active', lastLogin: '2023-11-29' },
    { id: 2, name: 'Sarah Smith', email: 'sarah@example.com', role: 'User', status: 'Active', lastLogin: '2023-11-28' },
    { id: 3, name: 'Michael Brown', email: 'michael@example.com', role: 'User', status: 'Inactive', lastLogin: '2023-10-15' },
    { id: 4, name: 'Emily Davis', email: 'emily@example.com', role: 'Manager', status: 'Active', lastLogin: '2023-11-30' },
    { id: 5, name: 'David Wilson', email: 'david@example.com', role: 'User', status: 'Suspended', lastLogin: '2023-09-20' },
    { id: 6, name: 'Jessica Taylor', email: 'jessica@example.com', role: 'User', status: 'Active', lastLogin: '2023-11-25' },
    { id: 7, name: 'Daniel Anderson', email: 'daniel@example.com', role: 'Viewer', status: 'Active', lastLogin: '2023-11-27' },
    { id: 8, name: 'Lisa Thomas', email: 'lisa@example.com', role: 'User', status: 'Inactive', lastLogin: '2023-08-10' },
    { id: 9, name: 'Robert Jackson', email: 'robert@example.com', role: 'Manager', status: 'Active', lastLogin: '2023-11-29' },
    { id: 10, name: 'Jennifer White', email: 'jennifer@example.com', role: 'User', status: 'Active', lastLogin: '2023-11-26' },
];

export const memberApi = {
  getMembers: async (params = {}) => {
    // In a real application, you would use the apiClient:
    // return apiClient.get('/members', { params });

    // Simulating API delay with global loading
    return apiClient.mock(MOCK_MEMBERS, 500);
  },

  updateMember: async (id, data) => {
    // return apiClient.put(`/members/${id}`, data);

    return apiClient.mock({ ...data, id }, 500);
  },

  createMember: async (data) => {
    // return apiClient.post('/members', data);

    // [MOCK ONLY]
    // In a real application, the ID is generated by the Database/Server.
    // The client should NOT generate numeric IDs.
    // We are generating it here only to simulate a successful server response.
    const newId = Math.floor(Math.random() * 1000) + 100;
    return apiClient.mock({ ...data, id: newId }, 500);
  }
};
